routes/web.php
<?php

use App\Http\Controllers\Account\ProfileController;
use App\Http\Controllers\Account\ProfilePasswordController;
use App\Http\Controllers\Auth\ExternalAuthenticationController;
use App\Http\Controllers\ChangelogController;
use App\Http\Controllers\ContextController;
use App\Http\Controllers\Exam\ExamController;
use App\Http\Controllers\Exam\ProcessController;
use App\Http\Controllers\Exam\TaskController;
use App\Http\Controllers\ExaminerController;
use App\Http\Controllers\Execution\Assessment\AssessmentIndexController;
use App\Http\Controllers\Execution\Assessment\AssessmentShowController;
use App\Http\Controllers\Execution\Assessment\AssessmentUpdateController;
use App\Http\Controllers\Execution\Csv\BookGeneratorController;
use App\Http\Controllers\Execution\Csv\ServerStudentController;
use App\Http\Controllers\Execution\CurrentExecutionController;
use App\Http\Controllers\Execution\ExecutionController;
use App\Http\Controllers\Execution\ExecutionStudentController;
use App\Http\Controllers\Execution\GroupController;
use App\Http\Controllers\Execution\Result\ResultIndexController;
use App\Http\Controllers\Execution\Result\ResultShowController;
use App\Http\Controllers\Execution\Result\ResultUpdateController;
use App\Http\Controllers\Execution\SharedResultsController;
use App\Http\Controllers\Execution\Task\TaskEditController;
use App\Http\Controllers\Execution\Task\TaskUpdateController;
use App\Http\Controllers\Export\BatchExportController;
use App\Http\Controllers\Export\BatchExportDownloadController;
use App\Http\Controllers\Export\ExportShowController;
use App\Http\Controllers\Export\ExportStoreController;
use App\Http\Controllers\Export\StudentExportController;
use App\Http\Controllers\ImpersonatedSessionController;
use App\Http\Controllers\RubricTaskGuidelineController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentStatusController;
use App\Http\Controllers\TerraformStateController;
use App\Http\Controllers\UserController;
use App\Livewire\Export\Index as ExecutionIndex;
use Illuminate\Auth\Middleware\Authenticate;
use Illuminate\Support\Facades\Route;

Route::auth([
    'register' => false,
    'reset' => true,
    'confirm' => true,
    'verify' => false,
]);

Route::get('sso/{service}/redirect', [ExternalAuthenticationController::class, 'create'])
    ->name('auth.redirect');
Route::get('sso/{service}/callback', [ExternalAuthenticationController::class, 'store'])
    ->name('auth.callback');

// Apply auth middleware to all routes
Route::middleware(Authenticate::class)->group(function (): void {
    Route::singleton('profile', ProfileController::class)
        ->only(['show', 'update']);

    Route::put('profile/password', [ProfilePasswordController::class, 'update'])
        ->name('profile.update-password');

    Route::get('changelog', ChangelogController::class)->name('changelog');

    // User routes
    Route::resource('users', UserController::class);

    Route::post('impersonate/{user:email}', [ImpersonatedSessionController::class, 'store'])
        ->name('impersonated-session.store');
    Route::delete('impersonate', [ImpersonatedSessionController::class, 'destroy'])
        ->name('impersonated-session.destroy');

    // Controller for student CRUD
    Route::get('students/status', [StudentStatusController::class, 'edit'])->name('students.archive.edit');
    Route::put('students/status', [StudentStatusController::class, 'update'])->name('students.archive.update');
    Route::resource('students', StudentController::class)
        ->parameter('students', 'student:sid');

    // Controller for examiner CRUD
    Route::resource('examiners', ExaminerController::class)
        ->parameter('examiners', 'examiner:abbreviation');

    // Routes related to the execution of an exam
    Route::get('executions/current', CurrentExecutionController::class)
        ->name('executions.current');
    Route::resource('executions', ExecutionController::class)
        ->parameter('executions', 'execution:slug');

    Route::resource('executions.groups', GroupController::class)
        ->only('create', 'store', 'show', 'edit', 'update', 'destroy')
        ->parameter('executions', 'execution:slug')
        ->parameter('groups', 'group:slug');

    Route::get('executions/{execution:slug}/students/examiners', [ExecutionStudentController::class, 'edit'])
        ->name('executions.students.edit');
    Route::put('executions/{execution:slug}/students/examiners', [ExecutionStudentController::class, 'update'])
        ->name('executions.students.update');

    Route::get('executions/{execution:slug}/students/tasks', TaskEditController::class)
        ->name('executions.students.tasks.edit');
    Route::put('executions/{execution:slug}/students/tasks', TaskUpdateController::class)
        ->name('executions.students.tasks.update');

    Route::get('executions/{execution:slug}/assessment', AssessmentIndexController::class)
        ->name('score.index');
    Route::get('executions/{execution:slug}/assessment/{student}/{process}', AssessmentShowController::class)
        ->name('score.show');
    Route::put('executions/{execution:slug}/assessment/{student}/{process}', AssessmentUpdateController::class)
        ->name('score.update');

    Route::get('executions/{execution:slug}/results/share', [SharedResultsController::class, 'show'])
        ->name('shared-results.show');
    Route::post('executions/{execution:slug}/results/share', [SharedResultsController::class, 'store'])
        ->name('shared-results.store');

    Route::get('executions/{execution}/results', ResultIndexController::class)
        ->name('result.index');
    Route::get('executions/{execution}/results/{student}/{process}', ResultShowController::class)
        ->name('result.show');
    Route::put('executions/{execution}/results/{student}/{process}', ResultUpdateController::class)
        ->name('result.update');

    Route::get('executions/{execution:slug}/exports', ExecutionIndex::class)
        ->can('executions.export', 'execution')
        ->name('executions.export.index');
    Route::post('executions/{execution:slug}/exports', ExportStoreController::class)
        ->name('executions.export.store');
    Route::get('executions/{execution:slug}/export/{date}', ExportShowController::class)
        ->name('executions.export.show');

    Route::post('executions/{execution:slug}/batch-exports', [BatchExportController::class, 'store'])
        ->name('executions.batch-export.store');

    Route::get('executions/{execution:slug}/batch-exports/{batchExport:id}', [BatchExportController::class, 'show'])
        ->name('executions.batch-export.show');

    Route::get('executions/{execution:slug}/batch-exports/{batchExport:id}/download', [BatchExportDownloadController::class, 'index'])
        ->name('executions.batch-export.download.index');

    Route::get('executions/{execution:slug}/batch-exports/{batchExport:id}/download/{student}', [BatchExportDownloadController::class, 'show'])
        ->name('executions.batch-export.download.show');

    Route::get('terraform', [TerraformStateController::class, 'index'])
        ->name('terraform.index');

    Route::get('executions/{execution}/students.csv', StudentExportController::class);
    Route::get('executions/{execution}/books.csv', BookGeneratorController::class);
    Route::get('executions/{execution}/server.csv', ServerStudentController::class);

    // Routes related to exams
    Route::resource('exams', ExamController::class)
        ->only(['index', 'show']);
    Route::resource('exams.tasks', TaskController::class)
        ->scoped(['exam', 'task'])
        ->only(['show']);
    Route::resource('exams.tasks.processes', ProcessController::class)
        ->scoped(['exam', 'task', 'process'])
        ->only(['show']);

    Route::resource('guidelines', RubricTaskGuidelineController::class)
        ->parameter('guidelines', 'rubric-task')
        ->only(['edit', 'update']);

    Route::resource('contexts', ContextController::class)
        ->except(['show', 'destroy']);

    Route::redirect('/', '/login');
});

app/Models/Student.php
<?php

namespace App\Models;

use App\Observers\StudentObserver;
use Database\Factories\StudentFactory;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasManyThrough;
use Illuminate\Database\Eloquent\SoftDeletes;
use Override;

#[ObservedBy(StudentObserver::class)]
class Student extends Model
{
    /** @use HasFactory<StudentFactory> */
    use HasFactory;

    use SoftDeletes;

    /** @var list<string> */
    protected $fillable = ['sid', 'first_name', 'middle_name', 'last_name', 'email', 'cohort', 'graduated'];

    /** Add global sorting scope to Execution. */
    #[Override]
    protected static function booted(): void
    {
        static::addGlobalScope('orderByFirstName', function (Builder $builder): void {
            $builder->orderBy('first_name');
        });
    }

    /** @return array<string, string> */
    #[Override]
    protected function casts(): array
    {
        return [
            'graduated' => 'boolean',
        ];
    }

    /**
     * Scope this query to only non-graduated students.
     *
     * @param  Builder<Student>  $query
     * @return Builder<Student>
     */
    public function scopeActive(Builder $query): Builder
    {
        return $this->scopeGraduated($query, false);
    }

    /**
     * Scope this query to only graduated students.
     *
     * @param  Builder<Student>  $query
     * @return Builder<Student>
     */
    public function scopeGraduated(Builder $query, bool $graduated = true): Builder
    {
        return $query->where('graduated', $graduated);
    }

    /** @return HasMany<ExecutionStudent, $this> */
    public function executionStudents(): HasMany
    {
        return $this->hasMany(ExecutionStudent::class, 'student_id');
    }

    /** @return BelongsToMany<Group, $this> */
    public function groups(): BelongsToMany
    {
        return $this->belongsToMany(Group::class, 'group_students', 'student_id', 'group_id');
    }

    /** @return HasManyThrough<ExecutionStudentTask, ExecutionStudent, $this> */
    public function executionStudentTasks(): HasManyThrough
    {
        return $this->hasManyThrough(ExecutionStudentTask::class, ExecutionStudent::class, 'student_id',
            'execution_student_id');
    }

    /** Format the full name of Student. */
    public function getFullName(): string
    {
        return collect([$this->first_name, $this->middle_name, $this->last_name])
            ->filter()
            ->join(' ');
    }

    public function getUsername(): string
    {
        return collect([$this->first_name[0] ?? null, $this->middle_name[0] ?? null, $this->last_name])
            ->filter()
            ->map(static fn (string $name): string => str($name)->slug('.')->transliterate()->value())
            ->join('.');
    }

    public function isGraduated(): bool
    {
        return $this->graduated;
    }

    #[Override]
    public function getRouteKeyName(): string
    {
        return 'sid';
    }
}

app/Http/Controllers/Api/StudentController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\StudentResource;
use App\Models\Student;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class StudentController extends Controller
{
    public function index(): AnonymousResourceCollection
    {
        return StudentResource::collection(
            Student::query()
                ->active()
                ->get()
        );
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentStoreRequest;
use App\Http\Requests\StudentUpdateRequest;
use App\Models\Student;
use App\Support\Breadcrumbs\Breadcrumbs;
use Exception;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class StudentController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Student::class, 'student');
    }

    /** Display a listing of the resource. */
    public function index(): View
    {
        $students = Student::active()->get();

        Breadcrumbs::make()
            ->add(__('views.students'), active: true)
            ->share();

        return view('students.index', [
            'students' => $students,
        ]);
    }

    /** Show the form for creating a new resource. */
    public function create(): View
    {
        Breadcrumbs::make()
            ->add(__('views.students'), route('students.index'))
            ->add('Toevoegen', active: true)
            ->share();

        return view('students.create');
    }

    /** Store a newly created resource in storage. */
    public function store(StudentStoreRequest $request): RedirectResponse
    {
        $student = $request->getStudent();
        $student->save();

        return to_route('students.index')
            ->with('success', trans('notifications.student.store'));
    }

    /** Display the specified resource. */
    public function show(Student $student): View
    {
        $student->loadMissing([
            'executionStudents.execution',
            'executionStudents.executionStudentTasks.task',
            'executionStudents.executionStudentTasks.context',
        ]);

        Breadcrumbs::make()
            ->add(__('views.students'), route('students.index'))
            ->add($student->getFullName(), active: true)
            ->share();

        return view('students.show', [
            'student' => $student,
        ]);
    }

    /** Show the form for editing the specified resource. */
    public function edit(Student $student): View
    {
        Breadcrumbs::make()
            ->add(__('views.students'), route('students.index'))
            ->add($student->getFullName(), route('students.show', $student))
            ->add('Bewerken', active: true)
            ->share();

        return view('students.edit', [
            'student' => $student,
        ]);
    }

    /** Update the specified resource in storage. */
    public function update(StudentUpdateRequest $request, Student $student): RedirectResponse
    {
        $student->update($request->getStudent());

        return to_route('students.show', $student)
            ->with('success', trans('notifications.student.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @throws Exception when no primary key exists on the model
     */
    public function destroy(Student $student): RedirectResponse
    {
        $student->delete();

        return to_route('students.index')
            ->with('danger', trans('notifications.student.destroy'));
    }
}

resources/views/students/create.blade.php
<x-layouts.app>
    <div class="container">
        <x-breadcrumbs />

        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8">
                <x-card>
                    <x-header title="Student toevoegen" />

                    <form action="{{ route('students.store') }}" method="post">
                        @csrf

                        <x-form.head title="Algemene informatie" />

                        <div class="row">
                            <div class="col-md-3 col-lg-2">
                                <x-input.text title="{{ __('Studentnummer') }}" name="sid" required autofocus />
                            </div>
                            <div class="col-md-3 col-lg-2">
                                <x-input.text
                                    title="{{ __('Cohort') }}"
                                    name="cohort"
                                    minlength="4"
                                    maxlength="4"
                                    required
                                />
                            </div>
                            <div class="col-md-6 col-lg-8">
                                <x-input.text title="{{ __('E-mail') }}" name="email" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <x-input.text title="{{ __('Voornaam') }}" name="first_name" required />
                            </div>
                            <div class="col-md-2">
                                <x-input.text title="{{ __('Tussenvoegsel') }}" name="middle_name" />
                            </div>
                            <div class="col-md-6">
                                <x-input.text title="{{ __('Achternaam') }}" name="last_name" required />
                            </div>
                        </div>

                        <x-form.create-actions cancel="{{ route('students.index') }}" />
                    </form>
                </x-card>
            </div>
        </div>
    </div>
</x-layouts.app>

resources/views/students/edit.blade.php
<x-layouts.app>
    <div class="container">
        <x-breadcrumbs />

        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8">
                <x-card>
                    <x-header title="Student bewerken" />

                    <form action="{{ route('students.update', $student) }}" method="post">
                        @csrf
                        @method('put')

                        <x-form.head title="Algemene informatie" />

                        <div class="row">
                            <div class="col-md-3 col-lg-2">
                                <x-input.text
                                    title="{{ __('Studentnummer') }}"
                                    name="sid"
                                    value="{{ $student->sid }}"
                                />
                            </div>
                            <div class="col-md-3 col-lg-2">
                                <x-input.text
                                    title="{{ __('Cohort') }}"
                                    name="cohort"
                                    minlength="4"
                                    maxlength="4"
                                    value="{{ $student->cohort }}"
                                    required
                                />
                            </div>
                            <div class="col-md-6 col-lg-8">
                                <x-input.text title="{{ __('E-mail') }}" name="email" value="{{ $student->email }}" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <x-input.text
                                    title="{{ __('Voornaam') }}"
                                    name="first_name"
                                    value="{{ $student->first_name }}"
                                    required
                                />
                            </div>
                            <div class="col-md-2">
                                <x-input.text
                                    title="{{ __('Tussenvoegsel') }}"
                                    name="middle_name"
                                    value="{{ $student->middle_name }}"
                                />
                            </div>
                            <div class="col-md-6">
                                <x-input.text
                                    title="{{ __('Achternaam') }}"
                                    name="last_name"
                                    value="{{ $student->last_name }}"
                                    required
                                />
                            </div>
                        </div>

                        <x-form.edit-actions cancel="{{ route('students.show', $student) }}" />
                    </form>
                </x-card>
            </div>
        </div>
    </div>

    <x-form.delete-modal route="{{ route('students.destroy', $student) }}">
        <x-slot name="title">
            @lang('Student verwijderen')
        </x-slot>
        Weet je zeker dat je "{{ $student->getFullName() }}" wilt verwijderen?
    </x-form.delete-modal>
</x-layouts.app>

resources/views/students/index.blade.php
<x-layouts.app>
    <div class="container-lg">
        <x-breadcrumbs />

        <x-header title="{{ __('Studenten') }}">
            @can('students.archive')
                <a
                    class="btn btn-sm btn-outline-secondary"
                    href="{{ route('students.archive.edit') }}"
                    data-toggle="tooltip"
                    title="Verbergen van studenten"
                >
                    @lang('Verbergen')
                </a>
            @endcan

            @can('create', \App\Models\Student::class)
                <a
                    class="btn btn-sm btn-primary"
                    href="{{ route('students.create') }}"
                    data-toggle="tooltip"
                    title="Toevoegen van student"
                >
                    @lang('Toevoegen')
                </a>
            @endcan
        </x-header>

        <div class="row justify-content-center">
            <div class="col">
                <div class="table-padded table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col" class="table-shrink-col">@lang('SID')</th>
                                <th scope="col">@lang('Voornaam')</th>
                                <th scope="col">@lang('Tussenvoegsel')</th>
                                <th scope="col">@lang('Achternaam')</th>
                                <th scope="col">@lang('Cohort')</th>
                                <th scope="col" class="text-end">
                                    <span class="visually-hidden">@lang('Acties')</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($students as $student)
                                <tr>
                                    <th scope="row">
                                        <a href="{{ route('students.show', $student) }}">{{ $student->sid }}</a>
                                    </th>
                                    <td>{{ $student->first_name }}</td>
                                    <td>{{ $student->middle_name }}</td>
                                    <td>{{ $student->last_name }}</td>
                                    <td>{{ $student->cohort }}</td>
                                    <td class="text-end">
                                        @can('update', $student)
                                            <a href="{{ route('students.edit', $student) }}">@lang('Bewerken')</a>
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-layouts.app>

resources/views/students/show.blade.php
<x-layouts.app>
    <div class="container">
        <x-breadcrumbs />

        <div class="row justify-content-center g-3">
            <div class="col-md-10 col-lg-8">
                <x-card>
                    <x-header title="Student">
                        @can('update', $student)
                            <a
                                class="btn btn-sm btn-primary"
                                href="{{ route('students.edit', $student) }}"
                                data-toggle="tooltip"
                                title="Bewerken van uitvoering"
                            >
                                @lang('Bewerken')
                            </a>
                        @endcan
                    </x-header>

                    <x-form.head title="Algemene informatie" />

                    <div class="row">
                        <div class="col-md-3 col-lg-2">
                            <x-label for="sid">@lang('Studentnummer')</x-label>
                            <x-input id="sid" name="sid" :value="$student->sid" readonly />
                        </div>
                        <div class="col-md-3 col-lg-2">
                            <x-label for="cohort">@lang('Cohort')</x-label>
                            <x-input id="cohort" name="cohort" :value="$student->cohort" readonly />
                        </div>
                        <div class="col-md-6 col-lg-8">
                            <x-label for="email">@lang('E-mail')</x-label>
                            <x-input id="email" name="email" :value="$student->email" readonly />
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-md-4">
                            <x-label for="first_name">@lang('Voornaam')</x-label>
                            <x-input id="first_name" name="first_name" :value="$student->first_name" readonly />
                        </div>
                        <div class="col-md-2">
                            <x-label for="middle_name">@lang('Tussenvoegsel')</x-label>
                            <x-input id="middle_name" name="middle_name" :value="$student->middle_name" readonly />
                        </div>
                        <div class="col-md-6">
                            <x-label for="last_name">@lang('Achternaam')</x-label>
                            <x-input id="last_name" name="last_name" :value="$student->last_name" readonly />
                        </div>
                    </div>
                </x-card>
            </div>
            <div class="col-md-10 col-lg-8">
                <x-card>
                    <x-header title="Vorige uitvoeringen"></x-header>
                    @empty($student->executionStudents)
                        <p>@lang('Geen uitvoeringen')</p>
                    @else
                        <ul class="mb-0">
                            @foreach ($student->executionStudents as $es)
                                <li>
                                    <a class="fw-bold" href="{{ route('executions.students.edit', $es->execution) }}">
                                        {{ $es->execution->name }} ({{ $es->execution->localizedStartDate() }})
                                    </a>
                                    <ul>
                                        @foreach ($es->executionStudentTasks->groupBy('context_id') as $est)
                                            <li>
                                                {{ sprintf('%s: %s', $est->pluck('task.name')->join(', '), $est->value('context.name')) }}
                                            </li>
                                        @endforeach
                                    </ul>
                                </li>
                            @endforeach
                        </ul>
                    @endempty
                </x-card>
            </div>
        </div>
    </div>
</x-layouts.app>