routes/web.php
<?php

use App\Http\Controllers\Account\ProfileController;
use App\Http\Controllers\Account\ProfilePasswordController;
use App\Http\Controllers\Auth\ExternalAuthenticationController;
use App\Http\Controllers\ChangelogController;
use App\Http\Controllers\ContextController;
use App\Http\Controllers\Exam\ExamController;
use App\Http\Controllers\Exam\ProcessController;
use App\Http\Controllers\Exam\TaskController;
use App\Http\Controllers\ExaminerController;
use App\Http\Controllers\Execution\Assessment\AssessmentIndexController;
use App\Http\Controllers\Execution\Assessment\AssessmentShowController;
use App\Http\Controllers\Execution\Assessment\AssessmentUpdateController;
use App\Http\Controllers\Execution\Csv\BookGeneratorController;
use App\Http\Controllers\Execution\Csv\ServerStudentController;
use App\Http\Controllers\Execution\CurrentExecutionController;
use App\Http\Controllers\Execution\ExecutionController;
use App\Http\Controllers\Execution\ExecutionStudentController;
use App\Http\Controllers\Execution\GroupController;
use App\Http\Controllers\Execution\Result\ResultIndexController;
use App\Http\Controllers\Execution\Result\ResultShowController;
use App\Http\Controllers\Execution\Result\ResultUpdateController;
use App\Http\Controllers\Execution\SharedResultsController;
use App\Http\Controllers\Execution\Task\TaskEditController;
use App\Http\Controllers\Execution\Task\TaskUpdateController;
use App\Http\Controllers\Export\BatchExportController;
use App\Http\Controllers\Export\BatchExportDownloadController;
use App\Http\Controllers\Export\ExportShowController;
use App\Http\Controllers\Export\ExportStoreController;
use App\Http\Controllers\Export\StudentExportController;
use App\Http\Controllers\ImpersonatedSessionController;
use App\Http\Controllers\RubricTaskGuidelineController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentStatusController;
use App\Http\Controllers\TerraformStateController;
use App\Http\Controllers\UserController;
use App\Livewire\Export\Index as ExecutionIndex;
use Illuminate\Auth\Middleware\Authenticate;
use Illuminate\Support\Facades\Route;

Route::auth([
    'register' => false,
    'reset' => true,
    'confirm' => true,
    'verify' => false,
]);

Route::get('sso/{service}/redirect', [ExternalAuthenticationController::class, 'create'])
    ->name('auth.redirect');
Route::get('sso/{service}/callback', [ExternalAuthenticationController::class, 'store'])
    ->name('auth.callback');

// Apply auth middleware to all routes
Route::middleware(Authenticate::class)->group(function (): void {
    Route::singleton('profile', ProfileController::class)
        ->only(['show', 'update']);

    Route::put('profile/password', [ProfilePasswordController::class, 'update'])
        ->name('profile.update-password');

    Route::get('changelog', ChangelogController::class)->name('changelog');

    // User routes
    Route::resource('users', UserController::class);

    Route::post('impersonate/{user:email}', [ImpersonatedSessionController::class, 'store'])
        ->name('impersonated-session.store');
    Route::delete('impersonate', [ImpersonatedSessionController::class, 'destroy'])
        ->name('impersonated-session.destroy');

    // Controller for student CRUD
    Route::get('students/status', [StudentStatusController::class, 'edit'])->name('students.archive.edit');
    Route::put('students/status', [StudentStatusController::class, 'update'])->name('students.archive.update');
    Route::resource('students', StudentController::class)
        ->parameter('students', 'student:sid');

    // Controller for examiner CRUD
    Route::resource('examiners', ExaminerController::class)
        ->parameter('examiners', 'examiner:abbreviation');

    // Routes related to the execution of an exam
    Route::get('executions/current', CurrentExecutionController::class)
        ->name('executions.current');
    Route::resource('executions', ExecutionController::class)
        ->parameter('executions', 'execution:slug');

    Route::resource('executions.groups', GroupController::class)
        ->only('create', 'store', 'show', 'edit', 'update', 'destroy')
        ->parameter('executions', 'execution:slug')
        ->parameter('groups', 'group:slug');

    Route::get('executions/{execution:slug}/students/examiners', [ExecutionStudentController::class, 'edit'])
        ->name('executions.students.edit');
    Route::put('executions/{execution:slug}/students/examiners', [ExecutionStudentController::class, 'update'])
        ->name('executions.students.update');

    Route::get('executions/{execution:slug}/students/tasks', TaskEditController::class)
        ->name('executions.students.tasks.edit');
    Route::put('executions/{execution:slug}/students/tasks', TaskUpdateController::class)
        ->name('executions.students.tasks.update');

    Route::get('executions/{execution:slug}/assessment', AssessmentIndexController::class)
        ->name('score.index');
    Route::get('executions/{execution:slug}/assessment/{student}/{process}', AssessmentShowController::class)
        ->name('score.show');
    Route::put('executions/{execution:slug}/assessment/{student}/{process}', AssessmentUpdateController::class)
        ->name('score.update');

    Route::get('executions/{execution:slug}/results/share', [SharedResultsController::class, 'show'])
        ->name('shared-results.show');
    Route::post('executions/{execution:slug}/results/share', [SharedResultsController::class, 'store'])
        ->name('shared-results.store');

    Route::get('executions/{execution}/results', ResultIndexController::class)
        ->name('result.index');
    Route::get('executions/{execution}/results/{student}/{process}', ResultShowController::class)
        ->name('result.show');
    Route::put('executions/{execution}/results/{student}/{process}', ResultUpdateController::class)
        ->name('result.update');

    Route::get('executions/{execution:slug}/exports', ExecutionIndex::class)
        ->can('executions.export', 'execution')
        ->name('executions.export.index');
    Route::post('executions/{execution:slug}/exports', ExportStoreController::class)
        ->name('executions.export.store');
    Route::get('executions/{execution:slug}/export/{date}', ExportShowController::class)
        ->name('executions.export.show');

    Route::post('executions/{execution:slug}/batch-exports', [BatchExportController::class, 'store'])
        ->name('executions.batch-export.store');

    Route::get('executions/{execution:slug}/batch-exports/{batchExport:id}', [BatchExportController::class, 'show'])
        ->name('executions.batch-export.show');

    Route::get('executions/{execution:slug}/batch-exports/{batchExport:id}/download', [BatchExportDownloadController::class, 'index'])
        ->name('executions.batch-export.download.index');

    Route::get('executions/{execution:slug}/batch-exports/{batchExport:id}/download/{student}', [BatchExportDownloadController::class, 'show'])
        ->name('executions.batch-export.download.show');

    Route::get('terraform', [TerraformStateController::class, 'index'])
        ->name('terraform.index');

    Route::get('executions/{execution}/students.csv', StudentExportController::class);
    Route::get('executions/{execution}/books.csv', BookGeneratorController::class);
    Route::get('executions/{execution}/server.csv', ServerStudentController::class);

    // Routes related to exams
    Route::resource('exams', ExamController::class)
        ->only(['index', 'show']);
    Route::resource('exams.tasks', TaskController::class)
        ->scoped(['exam', 'task'])
        ->only(['show']);
    Route::resource('exams.tasks.processes', ProcessController::class)
        ->scoped(['exam', 'task', 'process'])
        ->only(['show']);

    Route::resource('guidelines', RubricTaskGuidelineController::class)
        ->parameter('guidelines', 'rubric-task')
        ->only(['edit', 'update']);

    Route::resource('contexts', ContextController::class)
        ->except(['show', 'destroy']);

    Route::redirect('/', '/login');
});

app/Http/Controllers/Api/ExecutionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ExecutionResource;
use App\Models\Execution;
use Illuminate\Http\Resources\Json\ResourceCollection;

class ExecutionController extends Controller
{
    public function index(): ResourceCollection
    {
        $this->authorize('viewAny', Execution::class);

        $executions = Execution::query()
            ->has('terraformExecution')
            ->get();

        return ExecutionResource::collection($executions);
    }

    public function show(Execution $execution): ExecutionResource
    {
        $this->authorize('viewAny', Execution::class);

        return ExecutionResource::make($execution);
    }
}

app/Http/Controllers/Execution/Assessment/AssessmentIndexController.php
<?php

namespace App\Http\Controllers\Execution\Assessment;

use App\Exceptions\NoExaminerException;
use App\Http\Controllers\Controller;
use App\Models\Examiner;
use App\Models\Execution;
use App\Models\ExecutionStudentTask;
use App\Support\Breadcrumbs\Breadcrumbs;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Http\Request;

class AssessmentIndexController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @throws NoExaminerException
     * @throws AuthorizationException
     */
    public function __invoke(Request $request, Execution $execution): View
    {
        $this->authorize('executions.score', $execution);

        $execution->load([
            'groups.students',
            'exam.tasks.processes',
            'exam.tasks' => fn (HasMany $query) => $query->withCount('processes'),
            'students.executionStudentTasks',
        ]);

        try {
            $examiner = $request->user()?->getExaminer();
        } catch (NoExaminerException $e) {
            report($e);
            $examiner = null;
        }

        $students = $execution->students()
            ->unless(
                $examiner === null,
                fn ($query) => $query
                    ->whereHas(
                        'tasks',
                        fn ($query) => $this->hasExaminer($query, $examiner),
                    )
            )
            ->with([
                'student',
                'tasks',
                'executionStudentTasks.client',
                'executionStudentTasks.supervisor',
            ])
            ->get();

        Breadcrumbs::make()
            ->add('Uitvoeringen', route('executions.index'))
            ->add($execution->name, route('executions.show', $execution))
            ->add('Beoordelingen', route('score.index', $execution), true)
            ->share();

        return view('executions.assessments.index', [
            'examiner' => $examiner,
            'execution' => $execution,
            'tasks' => $execution->exam->tasks,
            'students' => $students,
        ]);
    }

    /**
     * Query to filter based on an examiner.
     *
     * @param  Builder<ExecutionStudentTask>  $query
     * @return Builder<ExecutionStudentTask>
     */
    public function hasExaminer(Builder $query, ?Examiner $examiner): Builder
    {
        return $query
            ->where(ExecutionStudentTask::CLIENT_COLUMN, $examiner?->id)
            ->orWhere(ExecutionStudentTask::SUPERVISOR_COLUMN, $examiner?->id);
    }
}

app/Http/Controllers/Execution/Assessment/AssessmentShowController.php
<?php

namespace App\Http\Controllers\Execution\Assessment;

use App\Exceptions\NoExaminerException;
use App\Exceptions\ScoringException;
use App\Http\Controllers\Controller;
use App\Models\Execution;
use App\Models\ExecutionStudent;
use App\Models\ExecutionStudentTask;
use App\Models\Process;
use App\Models\Student;
use App\Services\AnnotationService;
use App\Support\Breadcrumbs\Breadcrumbs;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Throwable;

class AssessmentShowController extends Controller
{
    public function __construct(
        private readonly AnnotationService $annotationService,
    ) {}

    /**
     * Handle the incoming request.
     *
     * @throws NoExaminerException when no examiner was found for the current user
     * @throws AuthorizationException
     * @throws Throwable
     */
    public function __invoke(Request $request, Execution $execution, Student $student, Process $process): RedirectResponse|View
    {
        $this->authorize('executions.score', $execution);

        $process->loadMissing([
            'task',
            'rubrics.tasks.items',
        ]);

        try {
            $examiner = $request->user()?->getExaminer();
        } catch (NoExaminerException) {
            return to_route('executions.show', $execution);
        }

        if ($examiner === null) {
            return to_route('executions.show', $execution);
        }

        $examinerId = $examiner->id;

        /** @var ExecutionStudent $es */
        $es = $execution->students()
            ->where('student_id', $student->id)
            ->whereHas('tasks', fn ($query): Builder => $query
                ->where('tasks.id', $process->task_id)
                ->where(fn ($query) => $query->orWhere([
                    ExecutionStudentTask::CLIENT_COLUMN => $examinerId,
                    ExecutionStudentTask::SUPERVISOR_COLUMN => $examinerId,
                ])))
            ->with(['student', 'tasks', 'processes'])
            ->firstOrFail();
        $est = $es->getTask($process->task) ?? throw new ScoringException;

        $role = $est->getExaminerRole($examiner);
        $column = $role->getScoreColumn();

        $selected = $est->scores()->pluck($column);
        $annotations = $this->annotationService->getExaminerAnnotations($est, $examiner);

        Breadcrumbs::make()
            ->add('Uitvoeringen', route('executions.index'))
            ->add($execution->name, route('executions.show', $execution))
            ->add('Beoordelingen', route('score.index', $execution))
            ->add($student->getFullName(), null, true)
            ->add($process->name, route('score.show', [$execution, $student, $process]), true)
            ->share();

        return view('executions.assessments.show', [
            'execution' => $execution,
            'student' => $student,
            'executionStudent' => $es,
            'task' => $process->task,
            'process' => $process,
            'selected' => $selected,
            'annotations' => $annotations,
            'client' => $est->client,
            'supervisor' => $est->supervisor,
        ]);
    }
}

app/Http/Controllers/Execution/Assessment/AssessmentUpdateController.php
<?php

namespace App\Http\Controllers\Execution\Assessment;

use App\Exceptions\NoExaminerException;
use App\Exceptions\ScoringException;
use App\Http\Controllers\Controller;
use App\Models\Execution;
use App\Models\ExecutionStudent;
use App\Models\ExecutionStudentTask;
use App\Models\Process;
use App\Models\Score;
use App\Models\Student;
use App\Models\User;
use App\Services\AnnotationService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Throwable;

class AssessmentUpdateController extends Controller
{
    public function __construct(
        private readonly AnnotationService $annotationService,
    ) {}

    /**
     * Handle the incoming request.
     *
     * @throws Throwable when the transaction couldn't be rolled back
     */
    public function __invoke(Request $request, Execution $execution, Student $student, Process $process): RedirectResponse
    {
        /** @var User $user */
        $user = $request->user();

        try {
            $examiner = $user->getExaminer();
            $task = $this->getExecutionStudentTask($execution, $student, $process);

            $role = $task->getExaminerRole($examiner);
            $column = $role->getScoreColumn(); // "client_score_id" or "supervisor_score_id"

            $rows = $request->collect('rows');

            /**
             * @var int $id
             * @var array<string, string> $row
             */
            foreach ($rows as $id => $row) {
                $score = Score::query()->updateOrCreate(['execution_student_task_id' => $task->id, 'rubric_task_id' => $id], [$column => $row['score'] ?? null]);
                $annotation = $row['annotation'] ?? null;
                $this->annotationService->update($score, $annotation, $examiner);
            }
        } catch (NoExaminerException) {
            return back()
                ->with('danger', trans('Deze gebruiker heeft geen koppeling met een examinator.'));
        }

        return to_route('score.show', [$execution, $student, $process]);
    }

    /**
     * Get the execution student task based on an execution, student and process.
     *
     * @throws ScoringException
     */
    private function getExecutionStudentTask(Execution $execution, Student $student, Process $process): ExecutionStudentTask
    {
        /** @var ExecutionStudent $executionStudent */
        $executionStudent = $execution->students()->firstWhere('student_id', $student->id)
            ?? throw new ScoringException('Execution student could not be found.');

        return $executionStudent->executionStudentTasks()->firstWhere('task_id', $process->task_id)
            ?? throw new ScoringException('Linked task could not be found.');
    }
}

resources/views/executions/assessments/index.blade.php
<x-layouts.app>
    <div class="container-xl">
        <x-breadcrumbs />

        <x-header title="{{ __('Beoordelingen') }}">
            <a
                class="btn btn-sm btn-outline-primary"
                data-bs-toggle="tooltip"
                href="{{ route('result.index', [$execution]) }}"
                title="Ga naar de uiteindelijke resultaten"
            >
                @lang('Resultaten')
            </a>
        </x-header>
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-bordered table-sm table-score-index">
                        <thead>
                            <tr class="table-primary">
                                <th rowspan="2" colspan="1">@lang('Student')</th>
                                @foreach ($tasks as $task)
                                    <th class="text-center" scope="col" colspan="{{ $task->processes_count }}">
                                        <strong>{{ data_get($task, 'name') }}</strong>
                                    </th>
                                @endforeach
                            </tr>
                            <tr class="table-primary">
                                @foreach ($tasks as $task)
                                    @foreach ($task->processes as $process)
                                        <th class="text-center" scope="col">
                                            <div
                                                data-bs-toggle="tooltip"
                                                data-bs-placement="top"
                                                title="{{ data_get($process, 'description') }}"
                                            >
                                                {{ data_get($process, 'name') }}
                                            </div>
                                        </th>
                                    @endforeach
                                @endforeach
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($students as $es)
                                <tr>
                                    <th scope="row" class="table-shrink-col">
                                        <a href="{{ route('students.show', $es->student) }}">
                                            {{ $es->student->getFullName() }}
                                        </a>
                                    </th>
                                    @foreach ($tasks as $task)
                                        @foreach ($task->processes as $process)
                                            @if ($es->tasks->contains($task))
                                                @if ($examiner)
                                                    <td
                                                        @class([
                                                            'text-center',
                                                            'fw-bold' => $es->isProcessFilled($task, $process, $es->getOtherExaminer($task, $examiner)),
                                                            'bg-ready' => $es->isProcessFilled($task, $process, $examiner),
                                                        ])
                                                    >
                                                        @if ($es->isTaskExaminer($task, $examiner))
                                                            <a
                                                                href="{{ route('score.show', [$execution, $es->student, $process]) }}"
                                                            >
                                                                {{ $es->getProcessProgress($task, $process, $examiner) }}
                                                            </a>
                                                        @else
                                                            {{ $process->name }}
                                                        @endif
                                                    </td>
                                                @else
                                                    <td class="text-center">{{ $process->name }}</td>
                                                @endif
                                            @else
                                                <td></td>
                                            @endif
                                        @endforeach
                                    @endforeach
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-layouts.app>